### DISCUSSION TITLE
v0.11.x - Deprecation of `bump-my-version`

### DISCUSSION THREAD

**Discussion by EdgyEdgemond** [NRWLDev/changelog-gen#25] [Announcements]
With the latest release, support for bump-my-version as an external dependency is being deprecated. In the next release it will be dropped entirely.

To support this configuration will need to migrate to the new format.

Currently both bumpversion and changelog-gen require configuration to use `changelog-gen`.

```toml
[tool.bumpversion]
current_version = "0.0.0"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[tool.changelog_gen]
release = true
commit = true
reject_empty = true
allowed_branches = [
    "main",
]
```

This has been simplified into a single set of configuration for `changelog-gen`, see the [documentation](https://nrwldev.github.io/changelog-gen/configuration/#versioning) for more detailed information.

```toml
[tool.changelog_gen]
current_version = "0.0.0"
reject_empty = true
allowed_branches = [
    "main",
]

[[tool.changelog_gen.files]]
filename = "README.md"

[[tool.changelog_gen.files]]
filename = "pyproject.toml"
pattern = 'version = "{version}"'
```
